### PR TITLE
[WiP] Added Nutrition example

### PR DESCRIPTION
**Pull request by xmnlab**
@andersy005 this is a work-in-progress PR. 

this will be a high-level example for processing semi-structured data.

the dataset used has ~30MB

at this moment xnd fails when read the dataset. I will take a look how to treat that on the example, maybe adding some clean task.

### CODE REVIEW

**Comment by andersy005** [comment]
I was playing with the following in xnd:
```python
from xnd import xnd
data = [{'name': 'Alice',
         'location': {'city': 'LA', 'state': 'CA'},
         'credits': [15, 20]
        },
        {'name': 'Bob',
         'location': {'city': 'NYC', 'state': 'NY'},
         'credits': [10, 20],
         
        }]

x = xnd(data)
x
```

```
xnd([{'name': 'Alice', 'location': {'city': 'LA', 'state': 'CA'}, 'credits': [15, 20]},
     {'name': 'Bob', 'location': {'city': 'NYC', 'state': 'NY'}, 'credits': [10, 20]}],
    type='2 * {name : string, location : {city : string, state : string}, credits : 2 * int64}')
```

And I did encounter the same value error when I switched the order of fields in the dictionary 
```python
data = [{'name': 'Alice',
         'credits': [15, 20],
         'location': {'city': 'LA', 'state': 'CA'}
        },
        {'name': 'Bob',
         'location': {'city': 'NYC', 'state': 'NY'},
         'credits': [10, 20],
         
        }]

x = xnd(data)
x
```
```
----------------------------------------
ValueErrorTraceback (most recent call last)
<ipython-input-17-4663334cbf33> in <module>()
     10         }]
     11 
---> 12 x = xnd(data)
     13 x

~/opt/miniconda3/envs/work/lib/python3.6/site-packages/xnd/__init__.py in __new__(cls, value, type, dtype, levels, typedef, dtypedef)
    124             type = typeof(value, dtype=dtype)
    125         else:
--> 126             type = typeof(value)
    127         return super().__new__(cls, type=type, value=value)
    128 

~/opt/miniconda3/envs/work/lib/python3.6/site-packages/xnd/__init__.py in typeof(value, dtype)
    141 
    142 def typeof(value, *, dtype=None):
--> 143     return ndt(_typeof(value, dtype=dtype))
    144 
    145 def _choose_dtype(lst):

~/opt/miniconda3/envs/work/lib/python3.6/site-packages/xnd/__init__.py in _typeof(value, dtype)
    167                         t = _typeof(x)
    168                         if t != dtype:
--> 169                             raise ValueError("dtype mismatch: have %s and %s" % (dtype, t))
    170 
    171             if opt:

ValueError: dtype mismatch: have {name: string, credits: 2 * int64, location: {city: string, state: string}} and {name: string, location: {city: string, state: string}, credits: 2 * int64}
```

And by looking at the traceback, I was able to understand the reason for the valueError. xnd is keeping the order of keys and this breaks the type inference when the data is not in the same order of keys

**Comment by andersy005** [comment]
I looked at the traceback and I was able to confirm that entries in the json dataset don't have the same keys and as a result xnd's type inference fails 
 
```
{id: int64, name: string, dataTypeName: string, fieldName: string, position: int64, renderTypeName: string, format: {}, flags: 1 * string}
{id: int64, name: string, dataTypeName: string, description: string, fieldName: string, position: int64, renderTypeName: string, tableColumnId: int64, width: int64, cachedContents: {largest: string, non_null: int64, average: string, null: int64, top: 6 * {item: string, count: int64}, smallest: string, sum: string}, format: {precisionStyle: string, noCommas: string, align: string}}
```

**Comment by xmnlab** [comment]
Great! thank you a lot. I will create a function to fix that in this analysis.

**Comment by xmnlab** [comment]
merge on green

**Comment by andersy005** [comment]
Looks good!

**Pull request merged**
