### PR TITLE
Fixing dependencies and logo path and style improvements

### PR DESCRIPTION
**Pull request by datapythonista**
The dependencies in `binder/environment.yml` are conflicting:
```
[mgarcia@localhost binder]$ conda env create
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python==3.6
  - xnd -> ndtypes==0.2.0dev3 -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.1,<6.2.0a0']
  - xnd -> ndtypes==0.2.0dev3 -> python[version='>=3.7,<3.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - xnd -> ndtypes==0.2.0dev3 -> python[version='>=3.7,<3.8.0a0'] -> readline[version='>=7.0,<8.0a0']
  - xnd -> ndtypes==0.2.0dev3 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
Use "conda search <package> --info" to see the dependencies for each package.
```

Not sure if there was a reason to pin Python, but at least the introduction notebook works well with Python 3.7.

Also fixed the logo path in the notebook which was broken, and address couple of pep8 and style things.

### CODE REVIEW

**Comment by datapythonista** [comment]
The travis build failed because they use an older version of glibc that doesn't seem to be supported by xnd. Probably worth merging this anyway, all the notebooks work well locally, and with some luck they'll in binder.

**Comment by rgommers** [comment]
The issue:
```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /home/travis/miniconda/envs/test/lib/python3.7/site-packages/gumath/../../../libgumath.so.0)
```
This I've seen before, let me attempt to fix it.

**Comment by rgommers** [comment]
Okay, upgrading to Xenial fixes the install problem, next issue is:
```
# using arrays from a dictionary
v = xnd_gumath({'x': [1, 2, 3], 'y': [4, 5, 6]})
# add
v['x'] + v['y']
------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-517cb77550bd> in <module>
      2 v = xnd_gumath({'x': ;34m[1, 2, 3], 'y': [4, 5, 6]})
      3 # add
----> 4 v['x'] + v['y']
~/build/xnd-project/xnd-notebooks/utils/math_utils.ipynb in _target(*args)
     51                             l_args[i] = xnd_gumath([v.value], type=_type)
     52 
---> 53                 return getattr(fn, op)(*tuple(l_args))
     54             return _target
     55 
ValueError: invalid dtype
ValueError: invalid dtype
```
That works locally too, so it's something odd again.

**Comment by rgommers** [comment]
Locally the following does fail:
```
eventsDS = xnd.xnd(data, type="20 * {id: int64, device: string}")
------------------

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-1f72a7c7018c> in <module>
----> 1 eventsDS = xnd.xnd(data, type="20 * {id: int64, device: string}")

~/anaconda3/envs/xnd/lib/python3.7/site-packages/xnd/__init__.py in __new__(cls, value, type, dtype, levels, typedef, dtypedef, device)
    131             device = (name, no)
    132 
--> 133         return super().__new__(cls, type=type, value=value, device=device)
    134 
    135     def __repr__(self):

TypeError: xnd: expected dict, not 'tuple'
TypeError: xnd: expected dict, not 'tuple'
```
That requires a fix to `tests/nbrun.py` it looks like, because that `TypeError` is the intended result. So I think this is good to merge as is so Binder works again. Then let's fix the next errors.

**Comment by rgommers** [comment]
Okay I'll merge it. Thanks @datapythonista!

**Comment by rgommers** [comment]
Binder indeed went from broken to fixed. I'll open new issues for the other things.

**Pull request merged**
